/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-01-18 12:53:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1609398800592L));
    _jspx_dependants.put("jar:file:/C:/Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMVC/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/board.css\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"boardViewForm\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"seq\" id=\"seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"pg\" id=\"pg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<table border=\"1\" width=\"500\" cellpadding=\"3\" cellspacing=\"0\" frame=\"hsides\" rules=\"rows\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\"><h3><span id=\"subjectSpan\"></span></h3></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"150\">글번호: <span id=\"seqSpan\"></span></td>\r\n");
      out.write("\t\t\t<td width=\"190\">작성자: <span id=\"idSpan\"></span></td>\r\n");
      out.write("\t\t\t<td width=\"150\">조회수: <span id=\"hitSpan\"></span></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"3\" height=\"300\" valign=\"top\" style=\"white-space: pre-line; word-break: break-all\"><span id=\"contentSpan\"></span>\r\n");
      out.write("\t\t\t</td> \r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("\t<input type=\"button\" value=\"목록\" onclick=\"location.href='../board/boardList?pg=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<span id=\"boardViewSpan\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"글수정\" onclick=\"mode(1)\">\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"글삭제\" onclick=\"mode(2)\">\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t <input type=\"button\" value=\"답글\" onclick=\"mode(3)\">\r\n");
      out.write("\t\t \r\n");
      out.write("</form>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function mode(num){\r\n");
      out.write("   if(num==1){//글수정\r\n");
      out.write("      document.boardViewForm.method=\"post\";\r\n");
      out.write("      document.boardViewForm.action=\"boardModifyForm\";\r\n");
      out.write("      document.boardViewForm.submit();\r\n");
      out.write("      \r\n");
      out.write("   }else if(num==2){//글삭제\r\n");
      out.write("      if(confirm(\"정말로 삭제하시겠습니까?\")){\r\n");
      out.write("         document.boardViewForm.method=\"post\";\r\n");
      out.write("         document.boardViewForm.action=\"boardDeleteForm\";\r\n");
      out.write("         document.boardViewForm.submit();\r\n");
      out.write("      }      \r\n");
      out.write("   }else if(num==3){//답글\r\n");
      out.write("\t\tdocument.boardViewForm.method=\"post\";\r\n");
      out.write("\t\tdocument.boardViewForm.action=\"boardReplyForm\";\r\n");
      out.write("\t\tdocument.boardViewForm.submit();\r\n");
      out.write("\t   \r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'post',\r\n");
      out.write("\t\turl: '/spring/board/getBoard',\r\n");
      out.write("\t\tdata: 'seq='+$('#seq').val(),\r\n");
      out.write("\t\tdataType : 'json',\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t//alert(JSON.stringify(data));\r\n");
      out.write("\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('#subjectSpan').text(data.boardDTO.subject);\r\n");
      out.write("\t\t\t$('#seqSpan').text(data.boardDTO.seq);\r\n");
      out.write("\t\t\t$('#idSpan').text(data.boardDTO.id);\r\n");
      out.write("\t\t\t$('#hitSpan').text(data.boardDTO.hit);\r\n");
      out.write("\t\t\t$('#contentSpan').text(data.boardDTO.content);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(data.memId == data.boardDTO.id)\r\n");
      out.write("\t\t\t\t$('#boardViewSpan').show();\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\t$('#boardViewSpan').hide();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(err){\r\n");
      out.write("\t\t\tconsole,log(err);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
