/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-01-31 12:38:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.imageboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class imageboardList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMVC/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1609398800592L));
    _jspx_dependants.put("jar:file:/C:/Spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMVC/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("th{\r\n");
      out.write("\tfont-size: 20pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td{\r\n");
      out.write("\tfont-size: 18pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#currentPaging {\r\n");
      out.write("\t\tcolor: red; \r\n");
      out.write("\t\ttext-decoration: underline;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\t}\r\n");
      out.write("#paging {\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcursor: pointer; /* 마우스를 가져다 데면 손가락 모양으로 마우스 모양을 바꿔줌 */\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<form id=\"imageboardListForm\" method=\"get\" action=\"imageboardDelete\">\r\n");
      out.write("\t<table id=\"imageboardListTable\" border=\"1\" cellpadding=\"3\" cellspacing=\"0\" frame=\"hsides\" rules=\"rows\">\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th width=\"180\"><input type=\"checkbox\" id=\"all\">글번호</th>\r\n");
      out.write("\t\t<th width=\"500\">이미지</th>\r\n");
      out.write("\t\t<th width=\"180\">상품명</th>\r\n");
      out.write("\t\t<th width=\"100\">단가</th>\r\n");
      out.write("\t\t<th width=\"180\">개수</th>\r\n");
      out.write("\t\t<th width=\"180\">합계</th>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t<div align=\"left\" style=\"float: left;\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"선택삭제\" id=\"choiceDeleteBtn\">\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div id=\"imageboardPagingDiv\" style=\"float: center; text-align: center;\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("</form>\t\t\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype: 'post',\r\n");
      out.write("\t\turl: '/spring/imageboard/getImageboardList',\r\n");
      out.write("\t\tdata: 'pg=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("\t\tdataType: 'json',\r\n");
      out.write("\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t/* alert(JSON.stringify(data.list)); */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//prepend 앞으로 들어가라.\r\n");
      out.write("\t\t\t//append 뒤로들어가라.\r\n");
      out.write("\t\t\t$.each(data.list, function(index, items){\r\n");
      out.write("\t\t\t\t$('<tr/>').append($('<td/>',{\r\n");
      out.write("\t\t\t\t\talign: 'center',\r\n");
      out.write("\t\t\t\t\ttext: items.seq\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}).prepend($('<input/>',{\r\n");
      out.write("\t\t\t\t\t\ttype: 'checkbox',\r\n");
      out.write("\t\t\t\t\t\tname: 'check',\r\n");
      out.write("\t\t\t\t\t\tvalue: items.seq\r\n");
      out.write("\t\t\t\t\t}))\r\n");
      out.write("\t\t\t\t).append($('<td/>',{\r\n");
      out.write("\t\t\t\t\talign: 'center',\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}).append($('<img/>',{\r\n");
      out.write("\t\t\t\t\t\tsrc: '/spring/storage/'+items.image1,\r\n");
      out.write("\t\t\t\t\t\tstyle: 'width: 70px; height: 70px; cursor: pointer;',\r\n");
      out.write("\t\t\t\t\t\tclass: items.seq+''\r\n");
      out.write("\t\t\t\t\t}))\t\r\n");
      out.write("\t\t\t\t).append($('<td/>',{\r\n");
      out.write("\t\t\t\t\talign: 'center',\r\n");
      out.write("\t\t\t\t\ttext: items.imageName\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})).append($('<td/>',{\r\n");
      out.write("\t\t\t\t\talign: 'center',\r\n");
      out.write("\t\t\t\t\ttext: items.imagePrice.toLocaleString()\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})).append($('<td/>',{\r\n");
      out.write("\t\t\t\t\talign: 'center',\r\n");
      out.write("\t\t\t\t\ttext: items.imageQty\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})).append($('<td/>',{\r\n");
      out.write("\t\t\t\t\talign: 'center',\r\n");
      out.write("\t\t\t\t\ttext: (items.imagePrice * items.imageQty).toLocaleString()\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})).appendTo($('#imageboardListTable'));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//이미지 보기\r\n");
      out.write("\t\t\t\t$('.'+items.seq).click(function(){\r\n");
      out.write("\t\t\t\t\tlocation.href='/spring/imageboard/imageboardView?seq='+items.seq+'&pg='+data.pg;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});//each\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//페이징처리\r\n");
      out.write("\t\t\t$('#imageboardPagingDiv').html(data.imageboardPaging.pagingHTML);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(err){\r\n");
      out.write("\t\t\tconsole.log(err);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function imageboardPaging(pg){\r\n");
      out.write("\t\r\n");
      out.write("\tlocation.href=\"imageboardList?pg=\"+pg;\r\n");
      out.write("\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//전체선택 또는 해제\r\n");
      out.write("$('#all').click(function(){\r\n");
      out.write("\t//alert($('#all').attr('checked'));// - checked 속성이 없어서 undefined 이나온다.\r\n");
      out.write("\t//alert($('#all').prop('checked'));// true/false\r\n");
      out.write("\t\r\n");
      out.write("\tif($('#all').prop('checked'))\r\n");
      out.write("\t\t$('input[name=check]').prop('checked',true); //name 변수가 check 인 태그의 속성 checked에, true 를 줘라.\r\n");
      out.write("\telse\r\n");
      out.write("\t\t$('input[name=check]').prop('checked',false);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//선택삭제\r\n");
      out.write("$('#choiceDeleteBtn').click(function(){\r\n");
      out.write("\tlet count = $('input[name=check]:checked').length; //name변수가 check 인 태그가 체크되어있는 것에 대한 갯수를 구해라.\r\n");
      out.write("\t\r\n");
      out.write("\tif(count == 0)\r\n");
      out.write("\t\talert('삭제할 항목을 선택하세요');\r\n");
      out.write("\telse{\r\n");
      out.write("\t\tif(confirm('정말로 삭제하시겠습니까?')){\r\n");
      out.write("\t\t\t$('#imageboardListForm').submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
